/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Feedback;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cyan
 */
public class FeedbackForm extends javax.swing.JFrame {

    /**
     * Creates new form FeedbackForm
     */
    private static final String URL = "jdbc:mysql://localhost:3306/feedback?useLegacyDatetimeCode=false&serverTimezone=UTC"; 
    private static final String USER = "root";
    private static final String PASS = "";   
    private String sql = "";
    Connection con = null;
    PreparedStatement pstmt  = null;
    ResultSet rs = null;
    ResultSetMetaData rsmd  = null;
    Statement stmt = null;
    
    
    private static final Scale scale = new Scale();
    
    public FeedbackForm() {
        initComponents();
        setStaffs();
    }
    
    public void setStaffs(){
        try {
            con = DriverManager.getConnection(URL, USER, PASS);
            sql = "SELECT name FROM staff";
            pstmt = con.prepareStatement(sql);
            rs = pstmt.executeQuery();
            comboStaffs.removeAllItems();
            while(rs.next()){
                comboStaffs.addItem(rs.getString("name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FeedbackForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // GETS THE SELECTED BUTTON FROM A BUTTON GROUP
    
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        grp1 = new javax.swing.ButtonGroup();
        grp2 = new javax.swing.ButtonGroup();
        grp3 = new javax.swing.ButtonGroup();
        grp4 = new javax.swing.ButtonGroup();
        grp5 = new javax.swing.ButtonGroup();
        grp6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        comboStaffs = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Poor1 = new javax.swing.JRadioButton();
        Uncertain1 = new javax.swing.JRadioButton();
        Fair1 = new javax.swing.JRadioButton();
        Good1 = new javax.swing.JRadioButton();
        Excellent1 = new javax.swing.JRadioButton();
        Poor2 = new javax.swing.JRadioButton();
        Uncertain2 = new javax.swing.JRadioButton();
        Fair2 = new javax.swing.JRadioButton();
        Good2 = new javax.swing.JRadioButton();
        Excellent2 = new javax.swing.JRadioButton();
        Poor3 = new javax.swing.JRadioButton();
        Excellent3 = new javax.swing.JRadioButton();
        Fair3 = new javax.swing.JRadioButton();
        Good3 = new javax.swing.JRadioButton();
        Uncertain3 = new javax.swing.JRadioButton();
        Excellent4 = new javax.swing.JRadioButton();
        Good4 = new javax.swing.JRadioButton();
        Fair4 = new javax.swing.JRadioButton();
        Poor4 = new javax.swing.JRadioButton();
        Uncertain4 = new javax.swing.JRadioButton();
        Excellent5 = new javax.swing.JRadioButton();
        Poor5 = new javax.swing.JRadioButton();
        Fair5 = new javax.swing.JRadioButton();
        Good5 = new javax.swing.JRadioButton();
        Uncertain5 = new javax.swing.JRadioButton();
        Poor6 = new javax.swing.JRadioButton();
        Uncertain6 = new javax.swing.JRadioButton();
        Fair6 = new javax.swing.JRadioButton();
        Good6 = new javax.swing.JRadioButton();
        Excellent6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboStaffs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStaffsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Communication Skills :");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Course Content Coverage :");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Effectiveness of Lectures :");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Teaching Pace :");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Willingness to work collaborately with the students : ");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("FEEDBACK");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Technical knowledge :");

        grp1.add(Poor1);
        Poor1.setForeground(new java.awt.Color(102, 102, 102));
        Poor1.setText("Poor");
        Poor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Poor1ActionPerformed(evt);
            }
        });

        grp1.add(Uncertain1);
        Uncertain1.setForeground(new java.awt.Color(102, 102, 102));
        Uncertain1.setText("Uncertain");
        Uncertain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uncertain1ActionPerformed(evt);
            }
        });

        grp1.add(Fair1);
        Fair1.setForeground(new java.awt.Color(102, 102, 102));
        Fair1.setText("Fair");
        Fair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fair1ActionPerformed(evt);
            }
        });

        grp1.add(Good1);
        Good1.setForeground(new java.awt.Color(102, 102, 102));
        Good1.setText("Good");

        grp1.add(Excellent1);
        Excellent1.setForeground(new java.awt.Color(102, 102, 102));
        Excellent1.setText("Excellent");

        grp2.add(Poor2);
        Poor2.setForeground(new java.awt.Color(102, 102, 102));
        Poor2.setText("Poor");

        grp2.add(Uncertain2);
        Uncertain2.setForeground(new java.awt.Color(102, 102, 102));
        Uncertain2.setText("Uncertain");
        Uncertain2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uncertain2ActionPerformed(evt);
            }
        });

        grp2.add(Fair2);
        Fair2.setForeground(new java.awt.Color(102, 102, 102));
        Fair2.setText("Fair");
        Fair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fair2ActionPerformed(evt);
            }
        });

        grp2.add(Good2);
        Good2.setForeground(new java.awt.Color(102, 102, 102));
        Good2.setText("Good");

        grp2.add(Excellent2);
        Excellent2.setForeground(new java.awt.Color(102, 102, 102));
        Excellent2.setText("Excellent");

        grp3.add(Poor3);
        Poor3.setForeground(new java.awt.Color(102, 102, 102));
        Poor3.setText("Poor");

        grp3.add(Excellent3);
        Excellent3.setForeground(new java.awt.Color(102, 102, 102));
        Excellent3.setText("Excellent");

        grp3.add(Fair3);
        Fair3.setForeground(new java.awt.Color(102, 102, 102));
        Fair3.setText("Fair");
        Fair3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fair3ActionPerformed(evt);
            }
        });

        grp3.add(Good3);
        Good3.setForeground(new java.awt.Color(102, 102, 102));
        Good3.setText("Good");

        grp3.add(Uncertain3);
        Uncertain3.setForeground(new java.awt.Color(102, 102, 102));
        Uncertain3.setText("Uncertain");
        Uncertain3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uncertain3ActionPerformed(evt);
            }
        });

        grp4.add(Excellent4);
        Excellent4.setForeground(new java.awt.Color(102, 102, 102));
        Excellent4.setText("Excellent");

        grp4.add(Good4);
        Good4.setForeground(new java.awt.Color(102, 102, 102));
        Good4.setText("Good");

        grp4.add(Fair4);
        Fair4.setForeground(new java.awt.Color(102, 102, 102));
        Fair4.setText("Fair");
        Fair4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fair4ActionPerformed(evt);
            }
        });

        grp4.add(Poor4);
        Poor4.setForeground(new java.awt.Color(102, 102, 102));
        Poor4.setText("Poor");

        grp4.add(Uncertain4);
        Uncertain4.setForeground(new java.awt.Color(102, 102, 102));
        Uncertain4.setText("Uncertain");
        Uncertain4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uncertain4ActionPerformed(evt);
            }
        });

        grp5.add(Excellent5);
        Excellent5.setForeground(new java.awt.Color(102, 102, 102));
        Excellent5.setText("Excellent");
        Excellent5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Excellent5ActionPerformed(evt);
            }
        });

        grp5.add(Poor5);
        Poor5.setForeground(new java.awt.Color(102, 102, 102));
        Poor5.setText("Poor");

        grp5.add(Fair5);
        Fair5.setForeground(new java.awt.Color(102, 102, 102));
        Fair5.setText("Fair");
        Fair5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fair5ActionPerformed(evt);
            }
        });

        grp5.add(Good5);
        Good5.setForeground(new java.awt.Color(102, 102, 102));
        Good5.setText("Good");

        grp5.add(Uncertain5);
        Uncertain5.setForeground(new java.awt.Color(102, 102, 102));
        Uncertain5.setText("Uncertain");
        Uncertain5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uncertain5ActionPerformed(evt);
            }
        });

        grp6.add(Poor6);
        Poor6.setForeground(new java.awt.Color(102, 102, 102));
        Poor6.setText("Poor");

        grp6.add(Uncertain6);
        Uncertain6.setForeground(new java.awt.Color(102, 102, 102));
        Uncertain6.setText("Uncertain");
        Uncertain6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uncertain6ActionPerformed(evt);
            }
        });

        grp6.add(Fair6);
        Fair6.setForeground(new java.awt.Color(102, 102, 102));
        Fair6.setText("Fair");
        Fair6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fair6ActionPerformed(evt);
            }
        });

        grp6.add(Good6);
        Good6.setForeground(new java.awt.Color(102, 102, 102));
        Good6.setText("Good");

        grp6.add(Excellent6);
        Excellent6.setForeground(new java.awt.Color(102, 102, 102));
        Excellent6.setText("Excellent");

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("BACK");
        jButton2.setMaximumSize(new java.awt.Dimension(86, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(86, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(comboStaffs, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Poor1)
                                .addComponent(Poor2)
                                .addComponent(Poor3)
                                .addComponent(Poor4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Poor5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Poor6))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Uncertain2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Fair2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Good2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(Uncertain4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Fair4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(Good4)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Excellent4)
                                        .addComponent(Excellent2)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Uncertain3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Fair3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Good3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Excellent3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Uncertain5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Fair5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Good5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Excellent5))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Uncertain1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Fair1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Good1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Excellent1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Uncertain6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Fair6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Good6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Excellent6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(comboStaffs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Poor1)
                    .addComponent(Uncertain1)
                    .addComponent(Fair1)
                    .addComponent(Good1)
                    .addComponent(Excellent1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Poor2)
                    .addComponent(Uncertain2)
                    .addComponent(Fair2)
                    .addComponent(Good2)
                    .addComponent(Excellent2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Poor3)
                    .addComponent(Uncertain3)
                    .addComponent(Fair3)
                    .addComponent(Good3)
                    .addComponent(Excellent3))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Poor4)
                    .addComponent(Uncertain4)
                    .addComponent(Fair4)
                    .addComponent(Good4)
                    .addComponent(Excellent4))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Poor5)
                    .addComponent(Uncertain5)
                    .addComponent(Fair5)
                    .addComponent(Good5)
                    .addComponent(Excellent5))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Poor6)
                    .addComponent(Uncertain6)
                    .addComponent(Fair6)
                    .addComponent(Good6)
                    .addComponent(Excellent6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboStaffsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStaffsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStaffsActionPerformed

    private void Uncertain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uncertain1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Uncertain1ActionPerformed

    private void Fair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fair1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fair1ActionPerformed

    private void Uncertain2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uncertain2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Uncertain2ActionPerformed

    private void Fair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fair2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fair2ActionPerformed

    private void Fair3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fair3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fair3ActionPerformed

    private void Uncertain3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uncertain3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Uncertain3ActionPerformed

    private void Fair4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fair4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fair4ActionPerformed

    private void Uncertain4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uncertain4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Uncertain4ActionPerformed

    private void Fair5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fair5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fair5ActionPerformed

    private void Uncertain5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uncertain5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Uncertain5ActionPerformed

    private void Uncertain6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uncertain6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Uncertain6ActionPerformed

    private void Fair6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fair6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Fair6ActionPerformed

    private void Poor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Poor1ActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_Poor1ActionPerformed
    
    private void clearRadioButtonSelections(){
        grp1.clearSelection();
        grp2.clearSelection();
        grp3.clearSelection();
        grp4.clearSelection();
        grp5.clearSelection();
        grp6.clearSelection();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            con = DriverManager.getConnection(URL, USER, PASS);
            sql = "INSERT INTO ratings VALUES(?,?,?,?,?,?,?,?)";
            pstmt = con.prepareStatement(sql);
            
            String name = comboStaffs.getSelectedItem().toString();
            int pOne = scale.returnPoints(getSelectedButtonText(grp1));
            // JOptionPane.showMessageDialog(this, pOne);
            int pTwo = scale.returnPoints(getSelectedButtonText(grp2));
            int pThree = scale.returnPoints(getSelectedButtonText(grp3));
            int pFour = scale.returnPoints(getSelectedButtonText(grp4));
            int pFive = scale.returnPoints(getSelectedButtonText(grp5));
            int pSix = scale.returnPoints(getSelectedButtonText(grp6));
                    
            Float avg = Float.valueOf((pOne + pTwo + pThree + pFour + pFive + pSix)) / 6;
            
            pstmt.setString(1, name);
            pstmt.setInt(2, pOne);
            pstmt.setInt(3, pTwo);
            pstmt.setInt(4, pThree);
            pstmt.setInt(5, pFour);
            pstmt.setInt(6, pFive);
            pstmt.setInt(7, pSix);
            pstmt.setFloat(8, avg);
            pstmt.executeUpdate();
           
            clearRadioButtonSelections();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(FeedbackForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Excellent5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Excellent5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Excellent5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Main session = new Main();
        session.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedbackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedbackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedbackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedbackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeedbackForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Excellent1;
    private javax.swing.JRadioButton Excellent2;
    private javax.swing.JRadioButton Excellent3;
    private javax.swing.JRadioButton Excellent4;
    private javax.swing.JRadioButton Excellent5;
    private javax.swing.JRadioButton Excellent6;
    private javax.swing.JRadioButton Fair1;
    private javax.swing.JRadioButton Fair2;
    private javax.swing.JRadioButton Fair3;
    private javax.swing.JRadioButton Fair4;
    private javax.swing.JRadioButton Fair5;
    private javax.swing.JRadioButton Fair6;
    private javax.swing.JRadioButton Good1;
    private javax.swing.JRadioButton Good2;
    private javax.swing.JRadioButton Good3;
    private javax.swing.JRadioButton Good4;
    private javax.swing.JRadioButton Good5;
    private javax.swing.JRadioButton Good6;
    private javax.swing.JRadioButton Poor1;
    private javax.swing.JRadioButton Poor2;
    private javax.swing.JRadioButton Poor3;
    private javax.swing.JRadioButton Poor4;
    private javax.swing.JRadioButton Poor5;
    private javax.swing.JRadioButton Poor6;
    private javax.swing.JRadioButton Uncertain1;
    private javax.swing.JRadioButton Uncertain2;
    private javax.swing.JRadioButton Uncertain3;
    private javax.swing.JRadioButton Uncertain4;
    private javax.swing.JRadioButton Uncertain5;
    private javax.swing.JRadioButton Uncertain6;
    private javax.swing.JComboBox<String> comboStaffs;
    private javax.swing.ButtonGroup grp1;
    private javax.swing.ButtonGroup grp2;
    private javax.swing.ButtonGroup grp3;
    private javax.swing.ButtonGroup grp4;
    private javax.swing.ButtonGroup grp5;
    private javax.swing.ButtonGroup grp6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
