/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CalculatorRegexTest;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author cyan
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelButtons = new javax.swing.JPanel();
        oneN = new javax.swing.JButton();
        twoN = new javax.swing.JButton();
        threeN = new javax.swing.JButton();
        fourN = new javax.swing.JButton();
        fiveN = new javax.swing.JButton();
        sixN = new javax.swing.JButton();
        nineN = new javax.swing.JButton();
        eightN = new javax.swing.JButton();
        sevenN = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        product = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        zeroN = new javax.swing.JButton();
        PanelDisplay = new javax.swing.JPanel();
        display = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(440, 460));

        PanelButtons.setBackground(new java.awt.Color(204, 204, 204));
        PanelButtons.setPreferredSize(new java.awt.Dimension(440, 430));

        oneN.setText("1");
        oneN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneNActionPerformed(evt);
            }
        });

        twoN.setText("2");
        twoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoNActionPerformed(evt);
            }
        });

        threeN.setText("3");
        threeN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeNActionPerformed(evt);
            }
        });

        fourN.setText("4");
        fourN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourNActionPerformed(evt);
            }
        });

        fiveN.setText("5");
        fiveN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveNActionPerformed(evt);
            }
        });

        sixN.setText("6");
        sixN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixNActionPerformed(evt);
            }
        });

        nineN.setText("9");
        nineN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineNActionPerformed(evt);
            }
        });

        eightN.setText("8");
        eightN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightNActionPerformed(evt);
            }
        });

        sevenN.setText("7");
        sevenN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenNActionPerformed(evt);
            }
        });

        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        product.setText("*");
        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });

        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        equals.setText("=");
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsActionPerformed(evt);
            }
        });

        zeroN.setText("0");
        zeroN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelButtonsLayout = new javax.swing.GroupLayout(PanelButtons);
        PanelButtons.setLayout(PanelButtonsLayout);
        PanelButtonsLayout.setHorizontalGroup(
            PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelButtonsLayout.createSequentialGroup()
                        .addComponent(fourN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fiveN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sixN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelButtonsLayout.createSequentialGroup()
                        .addComponent(oneN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(twoN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(threeN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelButtonsLayout.createSequentialGroup()
                        .addComponent(sevenN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zeroN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelButtonsLayout.createSequentialGroup()
                                .addComponent(eightN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nineN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(66, 66, 66)
                .addGroup(PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PanelButtonsLayout.setVerticalGroup(
            PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelButtonsLayout.createSequentialGroup()
                        .addGroup(PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oneN)
                            .addComponent(twoN)
                            .addComponent(threeN)
                            .addComponent(plus)
                            .addComponent(minus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourN)
                            .addComponent(fiveN)
                            .addComponent(sixN)
                            .addComponent(product)
                            .addComponent(divide)))
                    .addComponent(equals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nineN)
                    .addComponent(eightN)
                    .addComponent(sevenN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(zeroN)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        PanelDisplay.setBackground(new java.awt.Color(102, 102, 102));
        PanelDisplay.setForeground(new java.awt.Color(255, 255, 255));

        display.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDisplayLayout = new javax.swing.GroupLayout(PanelDisplay);
        PanelDisplay.setLayout(PanelDisplayLayout);
        PanelDisplayLayout.setHorizontalGroup(
            PanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display)
                .addContainerGap())
        );
        PanelDisplayLayout.setVerticalGroup(
            PanelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PanelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void oneNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneNActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '1');
    }//GEN-LAST:event_oneNActionPerformed

    private void twoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoNActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '2');
    }//GEN-LAST:event_twoNActionPerformed

    private void threeNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeNActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '3');
    }//GEN-LAST:event_threeNActionPerformed

    private void fourNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourNActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '4');
    }//GEN-LAST:event_fourNActionPerformed

    private void fiveNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveNActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '5');
    }//GEN-LAST:event_fiveNActionPerformed

    private void sixNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixNActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '6');
    }//GEN-LAST:event_sixNActionPerformed

    private void sevenNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenNActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '7');
    }//GEN-LAST:event_sevenNActionPerformed

    private void eightNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightNActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '8');
    }//GEN-LAST:event_eightNActionPerformed

    private void nineNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineNActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '9');
    }//GEN-LAST:event_nineNActionPerformed

    private void zeroNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroNActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '0');
    }//GEN-LAST:event_zeroNActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '+');
    }//GEN-LAST:event_plusActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '-');
    }//GEN-LAST:event_minusActionPerformed

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '*');
    }//GEN-LAST:event_productActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        // TODO add your handling code here:
        display.setText(display.getText() + '/');
    }//GEN-LAST:event_divideActionPerformed

    private void calculate() {
        try{
            String displayText = display.getText();
            String[] splitNos = displayText.split("[+-/*]");
            JOptionPane.showMessageDialog(this, splitNos);
            String[] splitOper = displayText.split("[0-9]");
            JOptionPane.showMessageDialog(this, splitOper);
            ArrayList<Float> splitNosList = new ArrayList<>();
            for (String str : splitNos) {
                splitNosList.add(Float.valueOf(str.trim()));
            }
            ArrayList<String> splitOperList = new ArrayList<>();
            for (String str : splitOper) {
                if (str.equals("")) {
                    continue;
                }
                splitOperList.add(str.trim());
            }
            
            while (!splitOperList.isEmpty()) {
                for (int No = 0, Op = 0; Op < splitOperList.size(); No++, Op++) {
                    if (splitOperList.get(Op).equals("/")) {
                        splitNosList.set(No, (splitNosList.get(No) / splitNosList.get(No + 1)));
                        splitNosList.remove(No + 1);
                        splitOperList.remove(Op);
                    }
                }
                for (int No = 0, Op = 0; Op < splitOperList.size(); No++, Op++) {
                    if (splitOperList.get(Op).equals("*")) {
                        splitNosList.set(No, (splitNosList.get(No) * splitNosList.get(No + 1)));
                        splitNosList.remove(No + 1);
                        splitOperList.remove(Op);
                    }
                }
                for (int No = 0, Op = 0; Op < splitOperList.size(); No++, Op++) {
                    if (splitOperList.get(Op).equals("+")) {
                        splitNosList.set(No, (splitNosList.get(No) + splitNosList.get(No + 1)));
                        splitNosList.remove(No + 1);
                        splitOperList.remove(Op);
                    }
                }
                for (int No = 0, Op = 0; Op < splitOperList.size(); No++, Op++) {
                    if (splitOperList.get(Op).equals("-")) {
                        splitNosList.set(No, (splitNosList.get(No) - splitNosList.get(No + 1)));
                        splitNosList.remove(No + 1);
                        splitOperList.remove(Op);
                    }
                }
            }
            display.setText(splitNosList.get(0).toString());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
            System.err.println(e);
        }
    }

    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
        // TODO add your handling code here:
        calculate();
    }//GEN-LAST:event_equalsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelButtons;
    private javax.swing.JPanel PanelDisplay;
    private javax.swing.JTextField display;
    private javax.swing.JButton divide;
    private javax.swing.JButton eightN;
    private javax.swing.JButton equals;
    private javax.swing.JButton fiveN;
    private javax.swing.JButton fourN;
    private javax.swing.JButton minus;
    private javax.swing.JButton nineN;
    private javax.swing.JButton oneN;
    private javax.swing.JButton plus;
    private javax.swing.JButton product;
    private javax.swing.JButton sevenN;
    private javax.swing.JButton sixN;
    private javax.swing.JButton threeN;
    private javax.swing.JButton twoN;
    private javax.swing.JButton zeroN;
    // End of variables declaration//GEN-END:variables
}
